---
project_name: egg

archives:
- id: egg
  files:
  - LICENSE
  format: tar.gz
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:    32bit
    amd64:  64bit
    darwin: macOS
    linux:  Linux

brews:
- name: egg
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  description: Extended go get - alternative for the standard `go get` with a few little but useful features.
  folder: Formula
  homepage: https://github.com/kamilsk/egg
  github:
    owner: kamilsk
    name:  homebrew-tap
  install: |
    bin.install "egg"
    output = Utils.popen_read("#{bin}/egg completion bash")
    (bash_completion/"egg").write output
    output = Utils.popen_read("#{bin}/egg completion zsh")
    (zsh_completion/"_egg").write output
    prefix.install_metafiles
  test: |
    system "#{bin}/egg --version"

builds:
- binary: egg
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: kamilsk
    name:  egg
