// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/golang/mock/mockgen"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/goreleaser/godownloader"
	_ "github.com/goreleaser/goreleaser"
	_ "golang.org/x/tools/cmd/goimports"
)

//go:generate go build -v -o=${ROOT}bin/mockgen github.com/golang/mock/mockgen
//go:generate go build -v -o=${ROOT}bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
//go:generate go build -v -o=${ROOT}bin/godownloader github.com/goreleaser/godownloader
//go:generate go build -v -o=${ROOT}bin/goreleaser github.com/goreleaser/goreleaser
//go:generate go build -v -o=${ROOT}bin/goimports golang.org/x/tools/cmd/goimports
